# Generated by Django 5.1.4 on 2026-07-09 17:27

import moka_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MokaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_trx_code', models.CharField(default=moka_django.models.generate_other_trx_code, editable=False, max_length=64, unique=True, verbose_name='Islem kodu (OtherTrxCode)')),
                ('code_for_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='3D dogrulama kodu (CodeForHash)')),
                ('virtual_pos_order_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Sanal POS siparis no (VirtualPosOrderId)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('currency', models.CharField(default='TL', max_length=3, verbose_name='Para birimi')),
                ('installment_number', models.PositiveSmallIntegerField(default=1, verbose_name='Taksit sayisi')),
                ('is_three_d', models.BooleanField(default=False, verbose_name='3D Secure odeme mi')),
                ('status', models.CharField(choices=[('created', 'Olusturuldu'), ('redirected', '3D dogrulamaya yonlendirildi'), ('success', 'Basarili'), ('failed', 'Basarisiz'), ('cancelled', 'Iptal edildi'), ('refunded', 'Iade edildi')], default='created', max_length=16, verbose_name='Durum')),
                ('result_code', models.CharField(blank=True, default='', max_length=128, verbose_name='Sonuc kodu')),
                ('result_message', models.CharField(blank=True, default='', max_length=255, verbose_name='Sonuc mesaji')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Aciklama')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Sonuclanma zamani')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma zamani')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme zamani')),
            ],
            options={
                'verbose_name': 'Moka odemesi',
                'verbose_name_plural': 'Moka odemeleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
